version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:RELEASE.2024-03-21T23-13-43Z
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
