openstack:
  hosts:
    ntnu-openstack:
      ansible_host: 129.241.152.31
      ansible_user: halvao
      k3s_become: true
      k3s_server:
        bind-address: 0.0.0.0
        write-kubeconfig-mode: 644
        disable:
          - traefik
          - servicelb

      k3s_server_manifests_urls:
        - url: https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
          filename: cert-manager.yml
        - url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          filename: ingress-nginx.yml

      k3s_server_manifests_templates:
        - admin-resources.yml.j2
        - dashboard.yml.j2
        - external-dns.yml.j2
        - ingress.yml.j2
        - lets-encrypt.yml.j2
        - pipeline-resources.yml.j2
