apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.name" . }}-data
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 6Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.name" . }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ "insight" | b64enc }} 
  MINIO_ACCESS_KEY: {{ "insight" | b64enc }} 
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "minio.name" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $minioPassword := (get $secretData "MINIO_ROOT_PASSWORD") | default (randAlphaNum 48 | b64enc) }}
  MINIO_ROOT_PASSWORD: {{ $minioPassword | quote }}
  MINIO_SECRET_KEY: {{ $minioPassword | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  serviceName: {{ include "minio.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}
    spec:
      containers:
      - name: {{ include "minio.name" . }}
        image: "minio/minio:RELEASE.2024-03-21T23-13-43Z"
        imagePullPolicy: IfNotPresent
        args: 
        - server 
        - /data 
        - --console-address 
        - ":9001"
        ports:
          - name: minio-api
            containerPort: {{ include "minio.port.api" . }}
            protocol: TCP
          - name: minio-ui
            containerPort: {{ include "minio.port.ui" . }}
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ include "minio.name" . }}
        volumeMounts:
          - name: {{ include "minio.name" . }}-data
            mountPath: /data
      volumes:
      - name: {{ include "minio.name" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "minio.name" . }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  selector:
    app: {{ include "minio.name" . }}
  ports:
  - name: api
    port: {{ include "minio.port.api" . }}
    targetPort: {{ include "minio.port.api" . }}
    protocol: TCP
  - name: ui
    port: {{ include "minio.port.ui" . }}
    targetPort: {{ include "minio.port.ui" . }}
    protocol: TCP
