---
- name: Install cluster
  hosts: openstack
  vars_files:
    - ../vars.yml
  roles:
    - name: Install k3s
      role: xanmanning.k3s
      vars:
        k3s_build_cluster: false
        k3s_state: installed
