spring:
  config:
    import: optional:file:.env[.properties]

no.isi.insight.planning:
  auth:
    token-issuer: ${AUTH_TOKEN_ISSUER:isi-insight}
    access-token:
      expiration-ms: ${AUTH_ACCESS_TOKEN_EXPIRATION_MS:300000}
      secret: ${AUTH_ACCESS_TOKEN_SECRET}
    refresh-token:
      expiration-ms: ${AUTH_REFRESH_TOKEN_EXPIRATION_MS:2592000000}
      secret: ${AUTH_REFRESH_TOKEN_SECRET}
