spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

no.isi.insight.planning:
  auth:
    token-issuer: ${AUTH_TOKEN_ISSUER:isi-insight}
    access-token:
      expiration-ms: ${AUTH_ACCESS_TOKEN_EXPIRATION_MS:300000}
      secret: ${AUTH_ACCESS_TOKEN_SECRET}
    refresh-token:
      expiration-ms: ${AUTH_REFRESH_TOKEN_EXPIRATION_MS:2592000000}
      secret: ${AUTH_REFRESH_TOKEN_SECRET}
  integration.nvdb:
    client-name: isi-insight-dev
    base-url: https://nvdbapiles-v3.atlas.vegvesen.no
