spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data.jdbc.repositories.enabled: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: ${MAIL_HOST:#{null}}
    username: ${MAIL_USERNAME:#{null}}
    password: ${MAIL_PASSWORD:#{null}}
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: ${MAIL_PORT:465}
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

springdoc:
  swagger-ui:
    path: /api/docs

no.isi.insight.planning:
  auth:
    token-issuer: ${AUTH_TOKEN_ISSUER:isi-insight}
    access-token:
      expiration-ms: ${AUTH_ACCESS_TOKEN_EXPIRATION_MS:300000}
      secret: ${AUTH_ACCESS_TOKEN_SECRET}
    refresh-token:
      expiration-ms: ${AUTH_REFRESH_TOKEN_EXPIRATION_MS:2592000000}
      secret: ${AUTH_REFRESH_TOKEN_SECRET}
  integration.nvdb:
    client-name: isi-insight-dev
    base-url: https://nvdbapiles-v3.atlas.vegvesen.no
  integration.minio:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
  integration.mail:
    enabled: ${MAIL_ENABLED:false}
    sender-address: ${MAIL_SENDER_ADDRESS:#{null}}

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
