
export enum CacheKey {
  USER_PROFILE = 'USER_PROFILE',
  PROJECT_LIST = 'PROJECT_LIST',
  PROJECT_DETAILS = 'PROJECT',
  PROJECT_PLAN_LIST = 'PROJECT_PLAN_LIST',
  PROJECT_PLAN_DETAILS = 'PROJECT_PLAN_DETAILS',
  VEHICLE_LIST = 'VEHICLE_LIST',
  VEHICLE_DETAILS = 'VEHICLE',
  ACTIVE_TRIP_LIST = 'ACTIVE_TRIP_LIST',
  TRIP_LIST = 'TRIP_LIST',
  TRIP_DETAILS = 'TRIP',
  CAPTURE_LOGS = 'CAPTURE_LOGS',
  PROJECT_RAILINGS = 'PROJECT_RAILINGS',
  TRIP_NOTE_LIST = 'TRIP_NOTE_LIST',
  TRIP_NOTE_DETAILS = 'TRIP_NOTE_DETAILS',
  USER_LIST = 'USER_LIST',
  USER_DETAILS = 'USER',
}
